### ISSUE TITLE
Is lymchat can't install/run under windows?

### ISSUE THREAD

**Issue by 9590** [tiensonqin/lymchat#3]
It's a nice project! 

I tried to run under windows, but failed. Is it only install/run under linux?

**Comment by tiensonqin** [comment]
Hi @9590, thanks.

Right now lymchat don't support windows.
To develop, you either need Mac OS or Linux.

**Comment by 9590** [comment]
Thanks you for replied so quickly! I'll try it!

**Comment by tiensonqin** [comment]
You're welcome.

Currently the api(server) part is still private(will eventually open source it),
so you need to mock some data.

**Comment by 9590** [comment]
OK, I am looking forward to seeing it happen.
