### ISSUE TITLE
a question

### ISSUE THREAD

**Issue by pishty1** [tiensonqin/lymchat#4]
Hello, 

i noticed in the code that you imported react-native-drawer but never actually use it, instead you used DrawerLayoutAndroid, just wondering your reason for abandoning react-native-drawer. The reason i ask is because i am in the middle of choosing between the 2 and i think i should use react-native-drawer because it works on both platforms so it would save me time and code. so am curious as to why u didnt use it.

Kind regards

**Comment by tiensonqin** [comment]
@pishty1 Sorry for late response.
The reason is that I use tabbar not drawer layout for iOS.

**Comment by pishty1** [comment]
ah ok cool, thank u for the response
